name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Specify the JDK distribution

      - name: Build with Gradle
        run: ./gradlew build  # Build your application

      - name: Run tests
        run: ./gradlew test  # Run your tests
